pub mod puzzle1;
pub mod puzzle2;
pub mod puzzle3;
// pub mod puzzle4;
// pub mod puzzle5;
// pub mod puzzle6;
// pub mod puzzle7;
// pub mod puzzle8;
// pub mod puzzle9;
// pub mod puzzle10;
// pub mod puzzle11;
// pub mod puzzle12;
// pub mod puzzle13;
// pub mod puzzle14;
//pub mod puzzle15;
pub mod puzzle16;
pub mod puzzle17;
// pub mod puzzle18;
pub mod puzzle19;
pub mod puzzle20;
// pub mod puzzle21;
// pub mod puzzle22;
// pub mod puzzle23;
// pub mod puzzle24;
// pub mod puzzle25;
